# Generated by Django 3.2.11 on 2022-03-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0002_deportista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deportista',
            new_name='deportistas',
        ),
    ]
