# Generated by Django 3.2.11 on 2022-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0004_rename_deportistas_deportista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportista',
            name='año',
        ),
        migrations.AddField(
            model_name='deportista',
            name='year',
            field=models.TextField(default='', max_length=250, verbose_name='year'),
            preserve_default=False,
        ),
    ]
