# Generated by Django 3.2.11 on 2022-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0005_auto_20220314_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='year',
            field=models.CharField(max_length=250, verbose_name='year'),
        ),
    ]
