# Generated by Django 3.2.11 on 2022-03-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0006_alter_deportista_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='deporte',
            field=models.TextField(max_length=250, verbose_name='deporte'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='nombre',
            field=models.TextField(max_length=250, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='year',
            field=models.TextField(max_length=250, verbose_name='year'),
        ),
    ]
